onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /hadamardtb/uut/W0
add wave -noupdate /hadamardtb/uut/W1
add wave -noupdate /hadamardtb/uut/W2
add wave -noupdate /hadamardtb/uut/W3
add wave -noupdate /hadamardtb/uut/W4
add wave -noupdate /hadamardtb/uut/W5
add wave -noupdate /hadamardtb/uut/W6
add wave -noupdate /hadamardtb/uut/W7
add wave -noupdate /hadamardtb/uut/W8
add wave -noupdate /hadamardtb/uut/W9
add wave -noupdate /hadamardtb/uut/W10
add wave -noupdate /hadamardtb/uut/W11
add wave -noupdate /hadamardtb/uut/W12
add wave -noupdate /hadamardtb/uut/W13
add wave -noupdate /hadamardtb/uut/W14
add wave -noupdate /hadamardtb/uut/W15
add wave -noupdate /hadamardtb/uut/clock
add wave -noupdate /hadamardtb/uut/reset
add wave -noupdate /hadamardtb/uut/enable
add wave -noupdate /hadamardtb/uut/S0
add wave -noupdate /hadamardtb/uut/S1
add wave -noupdate /hadamardtb/uut/S2
add wave -noupdate /hadamardtb/uut/S3
add wave -noupdate /hadamardtb/uut/S4
add wave -noupdate /hadamardtb/uut/S5
add wave -noupdate /hadamardtb/uut/S6
add wave -noupdate /hadamardtb/uut/S7
add wave -noupdate /hadamardtb/uut/S8
add wave -noupdate /hadamardtb/uut/S9
add wave -noupdate /hadamardtb/uut/S10
add wave -noupdate /hadamardtb/uut/S11
add wave -noupdate /hadamardtb/uut/S12
add wave -noupdate /hadamardtb/uut/S13
add wave -noupdate /hadamardtb/uut/S14
add wave -noupdate /hadamardtb/uut/S15
add wave -noupdate /hadamardtb/uut/saidaW
add wave -noupdate /hadamardtb/uut/a
add wave -noupdate /hadamardtb/uut/b
add wave -noupdate /hadamardtb/uut/saidaB
add wave -noupdate /hadamardtb/uut/c
add wave -noupdate /hadamardtb/uut/R0
add wave -noupdate /hadamardtb/uut/R1
add wave -noupdate /hadamardtb/uut/R2
add wave -noupdate /hadamardtb/uut/R3
add wave -noupdate /hadamardtb/uut/R4
add wave -noupdate /hadamardtb/uut/R5
add wave -noupdate /hadamardtb/uut/R6
add wave -noupdate /hadamardtb/uut/R7
add wave -noupdate /hadamardtb/uut/R8
add wave -noupdate /hadamardtb/uut/R9
add wave -noupdate /hadamardtb/uut/R10
add wave -noupdate /hadamardtb/uut/R11
add wave -noupdate /hadamardtb/uut/R12
add wave -noupdate /hadamardtb/uut/R13
add wave -noupdate /hadamardtb/uut/R14
add wave -noupdate /hadamardtb/uut/R15
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {64 ns}
